global.item_sprites = [
		[spr_items_helms, 0 ],
		spr_items_torsos,
		spr_items_gloves,
		spr_items_boots,
		spr_items_accessories,
		spr_items_necklaces,
		spr_items_rings,
		spr_items_daggers,
		spr_items_swords,
		spr_items_clubs,
		spr_items_staves,
		spr_items_sythes,
		spr_items_axes,
		spr_items_bows,
		spr_items_crossbows,
		spr_items_gloves,
		spr_items_shields,
		spr_items_ammo,
		spr_items_throwables,
		spr_items_bags,
		spr_items_foodstuff,
		spr_items_valuables,
		spr_items_relics
	];